name: "报告漏洞/问题"
description: "向我们报告漏洞/问题，让 PenMods 变得更好"
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写这份漏洞/问题反馈报告！
        > 请勿在这里反馈具有严重影响的漏洞, 相关问题请在聊天软件内私聊项目开发者并及时向网易有道反馈（如果是系统自身问题）

  - type: dropdown
    id: module
    attributes:
      label: 异常模块
      description: 出现问题的模块
      options:
        - PenMods (由Mod修改导致的)
        - YoudaoDictPen（词典笔主程序自身）
        - Services (PenMods相关服务，如更新服务)
    validations:
      required: true
  - type: dropdown
    id: model
    attributes:
      label: 词典笔型号
      multiple: false
      options:
        - YDP02x
        - YDPG-3
        - 其他
    validations:
      required: true
  - type: input
    id: modversion
    attributes:
      label: "PenMods 版本"
      placeholder: e.g. 1.1.7
    validations:
      required: true
  - type: input
    id: osversion
    attributes:
      label: 词典笔系统版本
      placeholder: e.g. 2.0.7
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么?
      description: |
        发生了什么? 请描述你的问题. 并告诉我们, 您希望我们做什么.
      placeholder: 描述你遇到的问题
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 复现此问题的步骤
      description: 尽可能清晰且详细的描述如何复现
      placeholder: |
        1. 做了什么
        2. ...
        3. ...
  - type: markdown
    attributes:
      value: |
        **可以在评论中进一步补充内容**
        ******
        再次感谢您对 PenMods Project 的贡献!
