name: "新功能请求/建议"
description: 提出意见建议，请求添加一个新的功能
labels: ["type: enhancement"]
body:
- type: markdown
  attributes:
    value: |
      感谢您花费宝贵时间填写这份新功能请求！
- type: checkboxes
  id: no-duplicate-issue
  attributes:
    label: 不要发送重复的问题报告
    description: 在提出问题前，请浏览/搜索已存在且被打开的Issue，确保它们没有被提出过。
    options:
      - label: 我已进行以上操作
        required: true
- type: textarea
  id: problem
  attributes:
    label: 您遇到了什么问题？
    description: 请简要描述遇到的问题
    placeholder: |
      e.g. 我发现词典笔在使用时...
- type: textarea
  id: solution
  attributes:
    label: 您认为还缺少什么？
    description: 请简单描述您设想的解决方案
    placeholder: |
      e.g. 添加一个...功能
- type: markdown
  attributes:
    value: |
      再次感谢您对 PenMods Project 的贡献！
